name: Publish InspIRCd Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
      
permissions:
  contents: read            # for checkout
  packages: write           # to push to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the code
      - uses: actions/checkout@v4

      # 2. Enable multi‑arch builds
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # 3. Log in to GHCR
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Determine which tag to push
      - name: Determine image tag
        id: tag
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            # e.g. v1.2.3 → 1.2.3
            echo "::set-output name=IMAGETAG::${GITHUB_REF_NAME#v}"
          else
            echo "::set-output name=IMAGETAG::latest"
          fi

      # 5. Build & push
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./inspircd
          file: ./inspircd/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/d2crashout/hassio-inspircd:${{ steps.tag.outputs.IMAGETAG }}
            ghcr.io/d2crashout/hassio-inspircd:latest
