name: Publish Docker Containers

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

permissions:
  contents: read       # checkout code
  packages: write      # allow pushing to GHCR


jobs:
  push-inspircd-container:
    if: ${{ !contains(github.event.head_commit.message, 'Bump add-on to') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # 1) Extract version from tag or fallback to commit SHA
      - name: Determine version
        id: ver
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "VERSION=dev-${SHORT_SHA}" >> $GITHUB_ENV
          fi

      # 2) Update config.json
      - name: Update config.json
        run: |
          jq --arg v "$VERSION" '.version = $v | .image |= sub(":[^:]+$"; ":" + $v)' inspircd/config.json > tmp.json
          mv tmp.json inspircd/config.json

      # 3) Commit and push back the bump
      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add inspircd/config.json
          git commit -m "Bump add-on to $VERSION"
          git push

      # 4) Build & push Docker image under that tag and latest
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./inspircd
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/d2crashout/hassio-inspircd:${{ env.VERSION }}
            ghcr.io/d2crashout/hassio-inspircd:latest
